# Configuration

# Site
title: 我的博客

author:
  name: Alvin Wang
  email: alvin.wang.csh@gmail.com
  
baseurl: "/blog"

# Extensions  
highlighter: pygments
  
comments:
  provider: duoshuo
  duoshuo:
    short_name : alvin
  disqus :
    short_name : alvin
  
