# Configuration

# Site
title: Alvin's Blog

author:
  name: Alvin Wang
  email: alvin.wang.csh@gmail.com
  
baseurl: "/blog"

# Extensions  
highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data", "tables"]
  
comments:
  provider: duoshuo
  duoshuo:
    short_name : alvin
  
